import React, { useState } from 'react';
import { router } from '@inertiajs/react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertTriangle } from 'lucide-react';

const AiDisclaimerModal = ({ isOpen }) => {
    const [agreed, setAgreed] = useState(false);
    const [submitting, setSubmitting] = useState(false);

    const handleSubmit = () => {
        if (!agreed) return;

        setSubmitting(true);
        router.post('/ai/disclaimer/agree', {}, {
            preserveScroll: true,
            onFinish: () => setSubmitting(false),
        });
    };

    return (
        <Dialog open={isOpen} onOpenChange={() => { }}>
            <DialogContent
                className="bg-stone-50 border-stone-200 shadow-xl sm:max-w-md [&>button]:hidden focus:outline-none gap-6"
                onPointerDownOutside={(e) => e.preventDefault()}
                onEscapeKeyDown={(e) => e.preventDefault()}
            >
                <DialogHeader className="flex flex-col items-center space-y-4 pb-2">
                    <div className="rounded-full bg-amber-100/50 p-3 ring-1 ring-amber-200/50">
                        <AlertTriangle className="h-8 w-8 text-amber-600" aria-hidden="true" strokeWidth={1.5} />
                    </div>
                    <div className="space-y-2 text-center">
                        <DialogTitle className="text-xl font-serif font-semibold text-slate-900 tracking-tight">
                            AI Features Disclaimer
                        </DialogTitle>
                        <DialogDescription className="text-slate-600 text-sm max-w-[85%] mx-auto">
                            Please read and accept the following terms to access AI features.
                        </DialogDescription>
                    </div>
                </DialogHeader>

                <div className="border border-stone-200 bg-white p-5 rounded-md h-[300px] overflow-y-auto text-sm text-slate-700 leading-relaxed shadow-sm">
                    <div className="space-y-5">
                        <p className="font-semibold text-slate-900">
                            Please read this carefully before relying on AI-generated content.
                        </p>

                        <p>
                            Content generated by the <strong>LiveYourBooks AI Mentor, Chat, and Summary features</strong> is designed to provide creative insights and personalized guidance.
                        </p>

                        <div className="space-y-3">
                            <h4 className="font-bold text-slate-900 uppercase text-xs tracking-wider border-b border-stone-100 pb-1">Core Limitations & Risks</h4>
                            <ol className="list-decimal pl-5 space-y-3 marker:text-slate-400 marker:font-medium">
                                <li>
                                    <span className="font-semibold text-slate-900">Hallucination (Factual Errors):</span> The AI model is a pattern-matching engine, not a fact-checker. It may generate information that is plausible but <span className="font-semibold text-red-600">factually incorrect</span>. Verify critical facts before acting.
                                </li>
                                <li>
                                    <span className="font-semibold text-slate-900">Personal Advice:</span> The Mentor feature provides generalized advice. It is <span className="font-semibold text-slate-900">not a substitute</span> for professional medical, legal, financial, or psychological consultation.
                                </li>
                                <li>
                                    <span className="font-semibold text-slate-900">Data Interpretation:</span> The AI interprets your tasks and habits subjectively and may contain bias derived from its training data.
                                </li>
                            </ol>
                        </div>

                        <div className="mt-4 p-3 bg-stone-100 rounded border border-stone-200 text-xs text-slate-600 italic">
                            By using our AI features, you acknowledge that LiveYourBooks is not responsible for any adverse outcome resulting from the application of AI-generated advice.
                        </div>
                    </div>
                </div>

                <div className="flex items-start space-x-3 pt-2 px-1">
                    <Checkbox
                        id="terms"
                        checked={agreed}
                        onCheckedChange={setAgreed}
                        className="mt-1 border-slate-400 data-[state=checked]:bg-slate-900 data-[state=checked]:border-slate-900 rounded-[4px]"
                    />
                    <label
                        htmlFor="terms"
                        className="text-sm font-medium leading-normal text-slate-700 peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer select-none"
                    >
                        I confirm I have read and understand the AI Guidance Disclaimer.
                    </label>
                </div>

                <DialogFooter className="mt-2 sm:justify-center">
                    <Button
                        onClick={handleSubmit}
                        disabled={!agreed || submitting}
                        className="w-full bg-slate-900 hover:bg-slate-800 text-stone-50 font-medium py-6 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                    >
                        {submitting ? 'Processing...' : 'Acknowledge & Continue'}
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    );
};

export default AiDisclaimerModal;
