import React, { useState } from 'react';

interface Props {
  className?: string;
  trigger?: React.ReactNode;
}

const AIGuidanceDisclaimer: React.FC<Props> = ({ className = '', trigger }) => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <div onClick={() => setIsOpen(true)} className={`cursor-pointer ${className}`}>
        {trigger || (
          <span className="text-xs text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 underline">
            AI Guidance Disclaimer
          </span>
        )}
      </div>

      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black bg-opacity-50">
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex justify-between items-start mb-4">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                  AI Guidance Disclaimer for LiveYourBooks
                </h2>
                <button
                  onClick={() => setIsOpen(false)}
                  className="text-gray-400 hover:text-gray-500 dark:hover:text-gray-300"
                >
                  <span className="sr-only">Close</span>
                  <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>

              <div className="prose dark:prose-invert max-w-none text-sm">
                <div className="bg-yellow-50 dark:bg-yellow-900/20 border-l-4 border-yellow-400 p-4 mb-4">
                  <p className="font-medium text-yellow-800 dark:text-yellow-200 m-0">
                    Please read this carefully before relying on AI-generated content.
                  </p>
                </div>

                <p>
                  Content generated by the LiveYourBooks AI Mentor, Chat, and Summary features (powered by Gemini AI) is designed to provide creative insights, context, and personalized guidance based on the text of your uploaded books and journal entries.
                </p>

                <h3 className="text-lg font-semibold mt-4 mb-2">Core Limitations & Risks</h3>

                <ul className="list-disc pl-5 space-y-2">
                  <li>
                    <strong>Hallucination (Factual Errors):</strong> The AI model is a powerful pattern-matching engine, not a fact-checker. It may occasionally generate information that is plausible, confident, but factually incorrect (a "hallucination"). You must verify any critical facts, statistics, or legal/medical advice before acting on it.
                  </li>
                  <li>
                    <strong>Personal Advice:</strong> The Mentor feature provides generalized advice based on its training data and your inputs. It is not a substitute for professional medical, legal, financial, or psychological consultation. Treat its recommendations as a starting point for reflection, not a directive.
                  </li>
                  <li>
                    <strong>Data Interpretation:</strong> The AI interprets the meaning and tone of your tasks and habits. Its interpretations are inherently subjective and may contain bias derived from its training data.
                  </li>
                </ul>

                <p className="mt-4 text-gray-600 dark:text-gray-400 italic">
                  By using our AI features, you acknowledge and agree that LiveYourBooks is not responsible for any adverse outcome resulting from the application of AI-generated advice or information.
                </p>
              </div>

              <div className="mt-6 flex justify-end">
                <button
                  onClick={() => setIsOpen(false)}
                  className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                >
                  I Understand
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default AIGuidanceDisclaimer;
